---
 - hosts: labpc
   become: true
   tasks:
       - name: make dir, type own, group and rights
         ansible.builtin.file:
           path: /home/ansible/tmp/
           state: directory
           owner: ansible
           group: ansible
           mode: '666'

